# Required libraries
suppressMessages(library(caret))
## Warning: package 'caret' was built under R version 3.2.3
## Warning: package 'lattice' was built under R version 3.2.2
suppressMessages(library(dplyr))
## Warning: package 'dplyr' was built under R version 3.2.2
suppressMessages(library(ggplot2))
suppressMessages(library(rpart.plot)) 
## Warning: package 'rpart.plot' was built under R version 3.2.3
## Warning: package 'rpart' was built under R version 3.2.3
suppressMessages(library(e1071))  # Skewness function use  
## Warning: package 'e1071' was built under R version 3.2.2
# Setting seed for reproducibility 
set.seed(123)
# Create Data repo
if(!dir.exists('./Data')){dir.create('./Data')}

# Create Figures repo
if(!dir.exists('./Figures')){dir.create('./Figures')}

# Load train data set
if(!file.exists('./Data/pml-training.csv')){
fileUrl<- 'https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv'
download.file(fileUrl,destfile='./Data/pml-training.csv',mode = 'wb')
}

# Load test data set
if(!file.exists('./Data/pml-testing.csv')){
fileUrl<- 'https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv'
download.file(fileUrl,destfile='./Data/pml-testing.csv',mode = 'wb')
}

# Load train data set
mydata_train <- read.csv("Data/pml-training.csv", na.strings=c("NA", ""))

# Load test data set
mydata_test <- read.csv("Data/pml-testing.csv", na.strings=c("NA", ""))

# Check dimension of data sets
dim(mydata_train); dim(mydata_test)
## [1] 19622   160
## [1]  20 160
# Check structure of train data set 
str(mydata_train)

## 'data.frame':    19622 obs. of  160 variables:
##  $ X                       : int  1 2 3 4 5 6 7 8 9 10 ...
##  $ user_name               : Factor w/ 6 levels "adelmo","carlitos",..: 2 2 2 2 2 2 2 2 2 2 ...
##  $ raw_timestamp_part_1    : int  1323084231 1323084231 1323084231 1323084232 1323084232 1323084232 1323084232 1323084232 1323084232 1323084232 ...
##  $ raw_timestamp_part_2    : int  788290 808298 820366 120339 196328 304277 368296 440390 484323 484434 ...
##  $ cvtd_timestamp          : Factor w/ 20 levels "02/12/2011 13:32",..: 9 9 9 9 9 9 9 9 9 9 ...
##  $ new_window              : Factor w/ 2 levels "no","yes": 1 1 1 1 1 1 1 1 1 1 ...
##  $ num_window              : int  11 11 11 12 12 12 12 12 12 12 ...
##  $ roll_belt               : num  1.41 1.41 1.42 1.48 1.48 1.45 1.42 1.42 1.43 1.45 ...
##  $ pitch_belt              : num  8.07 8.07 8.07 8.05 8.07 8.06 8.09 8.13 8.16 8.17 ...
##  $ yaw_belt                : num  -94.4 -94.4 -94.4 -94.4 -94.4 -94.4 -94.4 -94.4 -94.4 -94.4 ...
##  $ total_accel_belt        : int  3 3 3 3 3 3 3 3 3 3 ...
##  $ kurtosis_roll_belt      : Factor w/ 396 levels "-0.016850","-0.021024",..: NA NA NA NA NA NA NA NA NA NA ...
##  $ kurtosis_picth_belt     : Factor w/ 316 levels "-0.021887","-0.060755",..: NA NA NA NA NA NA NA NA NA NA ...
##  $ kurtosis_yaw_belt       : Factor w/ 1 level "#DIV/0!": NA NA NA NA NA NA NA NA NA NA ...
##  $ skewness_roll_belt      : Factor w/ 394 levels "-0.003095","-0.010002",..: NA NA NA NA NA NA NA NA NA NA ...
##  $ skewness_roll_belt.1    : Factor w/ 337 levels "-0.005928","-0.005960",..: NA NA NA NA NA NA NA NA NA NA ...
##  $ skewness_yaw_belt       : Factor w/ 1 level "#DIV/0!": NA NA NA NA NA NA NA NA NA NA ...
##  $ max_roll_belt           : num  NA NA NA NA NA NA NA NA NA NA ...
##  $ max_picth_belt          : int  NA NA NA NA NA NA NA NA NA NA ...
##  $ max_yaw_belt            : Factor w/ 67 levels "-0.1","-0.2",..: NA NA NA NA NA NA NA NA NA NA ...
##  $ min_roll_belt           : num  NA NA NA NA NA NA NA NA NA NA ...
##  $ min_pitch_belt          : int  NA NA NA NA NA NA NA NA NA NA ...
##  $ min_yaw_belt            : Factor w/ 67 levels "-0.1","-0.2",..: NA NA NA NA NA NA NA NA NA NA ...
##  $ amplitude_roll_belt     : num  NA NA NA NA NA NA NA NA NA NA ...
##  $ amplitude_pitch_belt    : int  NA NA NA NA NA NA NA NA NA NA ...
##  $ amplitude_yaw_belt      : Factor w/ 3 levels "#DIV/0!","0.00",..: NA NA NA NA NA NA NA NA NA NA ...
##  $ var_total_accel_belt    : num  NA NA NA NA NA NA NA NA NA NA ...
##  $ avg_roll_belt           : num  NA NA NA NA NA NA NA NA NA NA ...
##  $ stddev_roll_belt        : num  NA NA NA NA NA NA NA NA NA NA ...
##  $ var_roll_belt           : num  NA NA NA NA NA NA NA NA NA NA ...
##  $ avg_pitch_belt          : num  NA NA NA NA NA NA NA NA NA NA ...
##  $ stddev_pitch_belt       : num  NA NA NA NA NA NA NA NA NA NA ...
##  $ var_pitch_belt          : num  NA NA NA NA NA NA NA NA NA NA ...
##  $ avg_yaw_belt            : num  NA NA NA NA NA NA NA NA NA NA ...
##  $ stddev_yaw_belt         : num  NA NA NA NA NA NA NA NA NA NA ...
##  $ var_yaw_belt            : num  NA NA NA NA NA NA NA NA NA NA ...
##  $ gyros_belt_x            : num  0 0.02 0 0.02 0.02 0.02 0.02 0.02 0.02 0.03 ...
##  $ gyros_belt_y            : num  0 0 0 0 0.02 0 0 0 0 0 ...
##  $ gyros_belt_z            : num  -0.02 -0.02 -0.02 -0.03 -0.02 -0.02 -0.02 -0.02 -0.02 0 ...
##  $ accel_belt_x            : int  -21 -22 -20 -22 -21 -21 -22 -22 -20 -21 ...
##  $ accel_belt_y            : int  4 4 5 3 2 4 3 4 2 4 ...
##  $ accel_belt_z            : int  22 22 23 21 24 21 21 21 24 22 ...
##  $ magnet_belt_x           : int  -3 -7 -2 -6 -6 0 -4 -2 1 -3 ...
##  $ magnet_belt_y           : int  599 608 600 604 600 603 599 603 602 609 ...
##  $ magnet_belt_z           : int  -313 -311 -305 -310 -302 -312 -311 -313 -312 -308 ...
##  $ roll_arm                : num  -128 -128 -128 -128 -128 -128 -128 -128 -128 -128 ...
##  $ pitch_arm               : num  22.5 22.5 22.5 22.1 22.1 22 21.9 21.8 21.7 21.6 ...
##  $ yaw_arm                 : num  -161 -161 -161 -161 -161 -161 -161 -161 -161 -161 ...
##  $ total_accel_arm         : int  34 34 34 34 34 34 34 34 34 34 ...
##  $ var_accel_arm           : num  NA NA NA NA NA NA NA NA NA NA ...
##  $ avg_roll_arm            : num  NA NA NA NA NA NA NA NA NA NA ...
##  $ stddev_roll_arm         : num  NA NA NA NA NA NA NA NA NA NA ...
##  $ var_roll_arm            : num  NA NA NA NA NA NA NA NA NA NA ...
##  $ avg_pitch_arm           : num  NA NA NA NA NA NA NA NA NA NA ...
##  $ stddev_pitch_arm        : num  NA NA NA NA NA NA NA NA NA NA ...
##  $ var_pitch_arm           : num  NA NA NA NA NA NA NA NA NA NA ...
##  $ avg_yaw_arm             : num  NA NA NA NA NA NA NA NA NA NA ...
##  $ stddev_yaw_arm          : num  NA NA NA NA NA NA NA NA NA NA ...
##  $ var_yaw_arm             : num  NA NA NA NA NA NA NA NA NA NA ...
##  $ gyros_arm_x             : num  0 0.02 0.02 0.02 0 0.02 0 0.02 0.02 0.02 ...
##  $ gyros_arm_y             : num  0 -0.02 -0.02 -0.03 -0.03 -0.03 -0.03 -0.02 -0.03 -0.03 ...
##  $ gyros_arm_z             : num  -0.02 -0.02 -0.02 0.02 0 0 0 0 -0.02 -0.02 ...
##  $ accel_arm_x             : int  -288 -290 -289 -289 -289 -289 -289 -289 -288 -288 ...
##  $ accel_arm_y             : int  109 110 110 111 111 111 111 111 109 110 ...
##  $ accel_arm_z             : int  -123 -125 -126 -123 -123 -122 -125 -124 -122 -124 ...
##  $ magnet_arm_x            : int  -368 -369 -368 -372 -374 -369 -373 -372 -369 -376 ...
##  $ magnet_arm_y            : int  337 337 344 344 337 342 336 338 341 334 ...
##  $ magnet_arm_z            : int  516 513 513 512 506 513 509 510 518 516 ...
##  $ kurtosis_roll_arm       : Factor w/ 329 levels "-0.02438","-0.04190",..: NA NA NA NA NA NA NA NA NA NA ...
##  $ kurtosis_picth_arm      : Factor w/ 327 levels "-0.00484","-0.01311",..: NA NA NA NA NA NA NA NA NA NA ...
##  $ kurtosis_yaw_arm        : Factor w/ 394 levels "-0.01548","-0.01749",..: NA NA NA NA NA NA NA NA NA NA ...
##  $ skewness_roll_arm       : Factor w/ 330 levels "-0.00051","-0.00696",..: NA NA NA NA NA NA NA NA NA NA ...
##  $ skewness_pitch_arm      : Factor w/ 327 levels "-0.00184","-0.01185",..: NA NA NA NA NA NA NA NA NA NA ...
##  $ skewness_yaw_arm        : Factor w/ 394 levels "-0.00311","-0.00562",..: NA NA NA NA NA NA NA NA NA NA ...
##  $ max_roll_arm            : num  NA NA NA NA NA NA NA NA NA NA ...
##  $ max_picth_arm           : num  NA NA NA NA NA NA NA NA NA NA ...
##  $ max_yaw_arm             : int  NA NA NA NA NA NA NA NA NA NA ...
##  $ min_roll_arm            : num  NA NA NA NA NA NA NA NA NA NA ...
##  $ min_pitch_arm           : num  NA NA NA NA NA NA NA NA NA NA ...
##  $ min_yaw_arm             : int  NA NA NA NA NA NA NA NA NA NA ...
##  $ amplitude_roll_arm      : num  NA NA NA NA NA NA NA NA NA NA ...
##  $ amplitude_pitch_arm     : num  NA NA NA NA NA NA NA NA NA NA ...
##  $ amplitude_yaw_arm       : int  NA NA NA NA NA NA NA NA NA NA ...
##  $ roll_dumbbell           : num  13.1 13.1 12.9 13.4 13.4 ...
##  $ pitch_dumbbell          : num  -70.5 -70.6 -70.3 -70.4 -70.4 ...
##  $ yaw_dumbbell            : num  -84.9 -84.7 -85.1 -84.9 -84.9 ...
##  $ kurtosis_roll_dumbbell  : Factor w/ 397 levels "-0.0035","-0.0073",..: NA NA NA NA NA NA NA NA NA NA ...
##  $ kurtosis_picth_dumbbell : Factor w/ 400 levels "-0.0163","-0.0233",..: NA NA NA NA NA NA NA NA NA NA ...
##  $ kurtosis_yaw_dumbbell   : Factor w/ 1 level "#DIV/0!": NA NA NA NA NA NA NA NA NA NA ...
##  $ skewness_roll_dumbbell  : Factor w/ 400 levels "-0.0082","-0.0096",..: NA NA NA NA NA NA NA NA NA NA ...
##  $ skewness_pitch_dumbbell : Factor w/ 401 levels "-0.0053","-0.0084",..: NA NA NA NA NA NA NA NA NA NA ...
##  $ skewness_yaw_dumbbell   : Factor w/ 1 level "#DIV/0!": NA NA NA NA NA NA NA NA NA NA ...
##  $ max_roll_dumbbell       : num  NA NA NA NA NA NA NA NA NA NA ...
##  $ max_picth_dumbbell      : num  NA NA NA NA NA NA NA NA NA NA ...
##  $ max_yaw_dumbbell        : Factor w/ 72 levels "-0.1","-0.2",..: NA NA NA NA NA NA NA NA NA NA ...
##  $ min_roll_dumbbell       : num  NA NA NA NA NA NA NA NA NA NA ...
##  $ min_pitch_dumbbell      : num  NA NA NA NA NA NA NA NA NA NA ...
##  $ min_yaw_dumbbell        : Factor w/ 72 levels "-0.1","-0.2",..: NA NA NA NA NA NA NA NA NA NA ...
##  $ amplitude_roll_dumbbell : num  NA NA NA NA NA NA NA NA NA NA ...
##   [list output truncated]

# Find variables (without NAs)
NoNA_Var<- which(colSums(!is.na(mydata_train))==dim(mydata_train)[1])
# Take into account the above variables without the first seven variables
mydata_train <- mydata_train %>% select(NoNA_Var) %>% select(-c(1:7))
mydata_test <- mydata_test %>% select(NoNA_Var) %>% select(-c(1:7))

# Correlation values between variables 
correlations<-  cor(select(mydata_train,-classe))
# Cut off correlation over 0.9
highCorr<-  findCorrelation(correlations, cutoff=  0.9)
# Subset data with our correlation limit
mydata_train<- mydata_train %>% select(-highCorr)
mydata_test<- mydata_test %>% select(-highCorr)

# Preprocessing: scaling, skewness (without the outcome 'classe') 
trans<-  preProcess(select(mydata_train,-classe),method=  c('center','scale','BoxCox'))

# Transformed data (train and test) sets 
mydata_train_trans<- predict(trans,select(mydata_train,-classe))
mydata_test_trans<- predict(trans,select(mydata_test,-classe))

# Build the predictive model on the subtrain data set
DT_model<- train(classe~. , data=mydata_sub_train, method= 'rpart')
# Predict on the validation data set
prediction<- predict(DT_model, mydata_valid)
# Confusion matrix on the validation data set
confusionMatrix(prediction, mydata_valid$classe)

## Confusion Matrix and Statistics
## 
##           Reference
## Prediction    A    B    C    D    E
##          A 1015  308  304  258  149
##          B   16  262   26  132  132
##          C   68  155  280   62  168
##          D   17   34   74  155   23
##          E    0    0    0   36  249
## 
## Overall Statistics
##                                           
##                Accuracy : 0.4999          
##                  95% CI : (0.4841, 0.5156)
##     No Information Rate : 0.2845          
##     P-Value [Acc > NIR] : < 2.2e-16       
##                                           
##                   Kappa : 0.347           
##  Mcnemar's Test P-Value : < 2.2e-16       
## 
## Statistics by Class:
## 
##                      Class: A Class: B Class: C Class: D Class: E
## Sensitivity            0.9095  0.34519  0.40936  0.24106  0.34535
## Specificity            0.6370  0.90329  0.86014  0.95488  0.98876
## Pos Pred Value         0.4990  0.46127  0.38199  0.51155  0.87368
## Neg Pred Value         0.9465  0.85186  0.87335  0.86519  0.87026
## Prevalence             0.2845  0.19347  0.17436  0.16391  0.18379
## Detection Rate         0.2587  0.06679  0.07137  0.03951  0.06347
## Detection Prevalence   0.5185  0.14479  0.18685  0.07724  0.07265
## Balanced Accuracy      0.7732  0.62424  0.63475  0.59797  0.66706

# Plot the Decision Tree
png('./Figures/unnamed-chunk-13.png',width=800,height=600)

rpart.plot(DT_model$finalModel, main="Decision Tree", extra=102, under=T, faclen=0, cex = 1,branch = 1, type = 0, fallen.leaves = T)

dev.off()

## png 
##   2


# Predict on the validation data set
prediction <- predict(RF_model, mydata_valid)
# Confusion matrix on the validation data set
confusionMatrix(prediction, mydata_valid$classe)

## Confusion Matrix and Statistics
## 
##           Reference
## Prediction    A    B    C    D    E
##          A 1115    8    0    0    0
##          B    1  746    3    0    0
##          C    0    5  680    4    0
##          D    0    0    1  638    1
##          E    0    0    0    1  720
## 
## Overall Statistics
##                                           
##                Accuracy : 0.9939          
##                  95% CI : (0.9909, 0.9961)
##     No Information Rate : 0.2845          
##     P-Value [Acc > NIR] : < 2.2e-16       
##                                           
##                   Kappa : 0.9923          
##  Mcnemar's Test P-Value : NA              
## 
## Statistics by Class:
## 
##                      Class: A Class: B Class: C Class: D Class: E
## Sensitivity            0.9991   0.9829   0.9942   0.9922   0.9986
## Specificity            0.9971   0.9987   0.9972   0.9994   0.9997
## Pos Pred Value         0.9929   0.9947   0.9869   0.9969   0.9986
## Neg Pred Value         0.9996   0.9959   0.9988   0.9985   0.9997
## Prevalence             0.2845   0.1935   0.1744   0.1639   0.1838
## Detection Rate         0.2842   0.1902   0.1733   0.1626   0.1835
## Detection Prevalence   0.2863   0.1912   0.1756   0.1631   0.1838
## Balanced Accuracy      0.9981   0.9908   0.9957   0.9958   0.9992

# Names of first important variables 
Imp_vars<-rownames(varImp(RF_model)$importance)[1:30]
# Build the predictive model on the subtrain data set (with the most important predictors)
RF_model_2<- train(classe~., data=mydata_sub_train[c(Imp_vars,'classe')], method = "rf", trControl = control)
# Predict on the validation data set
prediction <- predict(RF_model_2, mydata_valid[c(Imp_vars,'classe')])
# Confusion matrix on the validation data set
confusionMatrix(prediction, mydata_valid$classe)

## Confusion Matrix and Statistics
## 
##           Reference
## Prediction    A    B    C    D    E
##          A 1112   11    1    2    0
##          B    2  740    4    0    0
##          C    1    7  676   11    1
##          D    1    0    3  629    3
##          E    0    1    0    1  717
## 
## Overall Statistics
##                                           
##                Accuracy : 0.9875          
##                  95% CI : (0.9835, 0.9907)
##     No Information Rate : 0.2845          
##     P-Value [Acc > NIR] : < 2.2e-16       
##                                           
##                   Kappa : 0.9842          
##  Mcnemar's Test P-Value : NA              
## 
## Statistics by Class:
## 
##                      Class: A Class: B Class: C Class: D Class: E
## Sensitivity            0.9964   0.9750   0.9883   0.9782   0.9945
## Specificity            0.9950   0.9981   0.9938   0.9979   0.9994
## Pos Pred Value         0.9876   0.9920   0.9713   0.9890   0.9972
## Neg Pred Value         0.9986   0.9940   0.9975   0.9957   0.9988
## Prevalence             0.2845   0.1935   0.1744   0.1639   0.1838
## Detection Rate         0.2835   0.1886   0.1723   0.1603   0.1828
## Detection Prevalence   0.2870   0.1902   0.1774   0.1621   0.1833
## Balanced Accuracy      0.9957   0.9865   0.9911   0.9880   0.9969

# Software environment
sessionInfo()

## R version 3.2.0 (2015-04-16)
## Platform: x86_64-w64-mingw32/x64 (64-bit)
## Running under: Windows 8 x64 (build 9200)
## 
## locale:
## [1] LC_COLLATE=English_United States.1252 
## [2] LC_CTYPE=English_United States.1252   
## [3] LC_MONETARY=English_United States.1252
## [4] LC_NUMERIC=C                          
## [5] LC_TIME=English_United States.1252    
## 
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## 
## other attached packages:
## [1] e1071_1.6-7      rpart.plot_1.5.3 rpart_4.1-10     dplyr_0.4.3     
## [5] caret_6.0-62     ggplot2_1.0.1    lattice_0.20-33 
## 
## loaded via a namespace (and not attached):
##  [1] Rcpp_0.12.2        formatR_1.2.1      nloptr_1.0.4      
##  [4] plyr_1.8.3         class_7.3-14       iterators_1.0.8   
##  [7] tools_3.2.0        digest_0.6.8       lme4_1.1-10       
## [10] evaluate_0.8       nlme_3.1-122       gtable_0.1.2      
## [13] mgcv_1.8-10        Matrix_1.2-0       foreach_1.4.3     
## [16] DBI_0.3.1          yaml_2.1.13        parallel_3.2.0    
## [19] SparseM_1.7        proto_0.3-10       stringr_1.0.0     
## [22] knitr_1.11         MatrixModels_0.4-1 stats4_3.2.0      
## [25] grid_3.2.0         nnet_7.3-11        R6_2.1.1          
## [28] rmarkdown_0.9      minqa_1.2.4        reshape2_1.4.1    
## [31] car_2.1-1          magrittr_1.5       scales_0.3.0      
## [34] codetools_0.2-14   htmltools_0.2.6    MASS_7.3-45       
## [37] splines_3.2.0      assertthat_0.1     pbkrtest_0.4-4    
## [40] colorspace_1.2-6   quantreg_5.19      stringi_1.0-1     
## [43] lazyeval_0.1.10    munsell_0.4.2
